#!/usr/bin/env bash
# =============================================================================
# hooks/notify-team.sh  —  OpenCode Stop hook
#
# Fires automatically when the AI session ends (Stop event).
# Summarises everything that changed during the session and
# sends a team notification.
#
# Notification channels (configure below):
#   - Console output (always)
#   - Saves TEAM_NOTIFICATION.md (always)
#   - Slack webhook (set SLACK_WEBHOOK_URL in .env or environment)
#   - MS Teams webhook (set TEAMS_WEBHOOK_URL in .env or environment)
# =============================================================================
set -uo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="$ROOT_DIR/backend"
FRONTEND_DIR="$ROOT_DIR/frontend"
NOTIF_FILE="$ROOT_DIR/TEAM_NOTIFICATION.md"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'
BOLD='\033[1m'; RESET='\033[0m'
sep() { echo -e "${BOLD}══════════════════════════════════════════${RESET}"; }

# ── Load .env if present (for webhook URLs) ─────────────────────────────────
[[ -f "$ROOT_DIR/.env" ]] && set -a && source "$ROOT_DIR/.env" && set +a

SLACK_WEBHOOK_URL="${SLACK_WEBHOOK_URL:-}"
TEAMS_WEBHOOK_URL="${TEAMS_WEBHOOK_URL:-}"

# ── Collect session context ──────────────────────────────────────────────────
DATE=$(date '+%Y-%m-%d %H:%M')
BRANCH=$(git -C "$ROOT_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
AUTHOR=$(git -C "$ROOT_DIR" config user.name 2>/dev/null || echo "Developer")

# Files changed since last commit
CHANGED=$(git -C "$ROOT_DIR" diff --name-only HEAD 2>/dev/null || true)
STAGED=$(git -C "$ROOT_DIR" diff --cached --name-only 2>/dev/null || true)
ALL_CHANGED=$(echo -e "$CHANGED\n$STAGED" | sort -u | grep -v '^$' || true)
CHANGED_COUNT=$(echo "$ALL_CHANGED" | grep -c . || echo 0)

# Module detection
BACKEND_CHANGED=$(echo "$ALL_CHANGED" | grep -c "backend/" || echo 0)
FRONTEND_CHANGED=$(echo "$ALL_CHANGED" | grep -c "frontend/" || echo 0)
HOOKS_CHANGED=$(echo "$ALL_CHANGED" | grep -c "hooks/" || echo 0)

# Last commit message
LAST_COMMIT_MSG=$(git -C "$ROOT_DIR" log -1 --pretty="%s" 2>/dev/null || echo "(uncommitted changes)")

# Test status (read from baseline, don't re-run)
SPRING_STATUS="Not run this session"
REACT_STATUS="Not run this session"
[[ -f /tmp/spring_last_result.txt ]] && SPRING_STATUS=$(cat /tmp/spring_last_result.txt)
[[ -f /tmp/react_last_result.txt  ]] && REACT_STATUS=$(cat /tmp/react_last_result.txt)

# ── Build the notification content ──────────────────────────────────────────
SUMMARY=""
[[ $BACKEND_CHANGED -gt 0 ]]  && SUMMARY+="Spring Boot ($BACKEND_CHANGED file(s)) | "
[[ $FRONTEND_CHANGED -gt 0 ]] && SUMMARY+="React ($FRONTEND_CHANGED file(s)) | "
[[ $HOOKS_CHANGED -gt 0 ]]    && SUMMARY+="Hooks updated | "
SUMMARY="${SUMMARY% | }"
[[ -z "$SUMMARY" ]] && SUMMARY="Configuration / documentation update"

# ── Print to console ─────────────────────────────────────────────────────────
echo ""
sep
echo -e "${BOLD}  TEAM NOTIFICATION${RESET}"
sep
echo -e "${CYAN}  Developer :${RESET} $AUTHOR"
echo -e "${CYAN}  Branch    :${RESET} $BRANCH"
echo -e "${CYAN}  Date      :${RESET} $DATE"
echo -e "${CYAN}  Summary   :${RESET} $SUMMARY"
echo ""
echo -e "${BOLD}  Files changed ($CHANGED_COUNT):${RESET}"
if [[ -n "$ALL_CHANGED" ]]; then
  echo "$ALL_CHANGED" | while read -r f; do [[ -n "$f" ]] && echo "    → $f"; done
else
  echo "    (no uncommitted changes)"
fi
echo ""
echo -e "${BOLD}  Last commit:${RESET} $LAST_COMMIT_MSG"
sep
echo ""

# ── Write TEAM_NOTIFICATION.md ───────────────────────────────────────────────
cat > "$NOTIF_FILE" <<EOF
# Team Notification — AI Session Complete

| Field      | Value                          |
|------------|--------------------------------|
| Developer  | $AUTHOR                        |
| Branch     | \`$BRANCH\`                     |
| Date       | $DATE                          |
| Changes    | $SUMMARY                       |

## Files Modified This Session ($CHANGED_COUNT)

$(echo "$ALL_CHANGED" | sed 's/^/- /' | grep -v '^- $' || echo "- None (no uncommitted changes)")

## Last Commit

> $LAST_COMMIT_MSG

## Impact Summary

$(  [[ $BACKEND_CHANGED -gt 0 ]]  && echo "- **Backend:** $BACKEND_CHANGED Java file(s) modified"
    [[ $FRONTEND_CHANGED -gt 0 ]] && echo "- **Frontend:** $FRONTEND_CHANGED React file(s) modified"
    [[ $HOOKS_CHANGED -gt 0 ]]    && echo "- **CI/Hooks:** Hook configuration updated"
    [[ $BACKEND_CHANGED -eq 0 && $FRONTEND_CHANGED -eq 0 && $HOOKS_CHANGED -eq 0 ]] && \
      echo "- Configuration or documentation changes only")

## Next Steps

- [ ] Review changes locally
- [ ] Run \`bash hooks/pre-push.sh\` to validate before pushing
- [ ] Open a Pull Request on GitHub
- [ ] Share \`pr-summary.md\` in the PR description
- [ ] Request peer review

---
*Auto-generated by ai-hooks-demo notify-team hook*
EOF

echo -e "${GREEN}  Notification saved to TEAM_NOTIFICATION.md${RESET}"

# ── Slack notification (optional) ────────────────────────────────────────────
if [[ -n "$SLACK_WEBHOOK_URL" ]]; then
  SLACK_PAYLOAD=$(cat <<JSON
{
  "text": "*AI Session Complete* — $AUTHOR on \`$BRANCH\`",
  "attachments": [{
    "color": "good",
    "fields": [
      { "title": "Summary",        "value": "$SUMMARY",       "short": false },
      { "title": "Files Changed",  "value": "$CHANGED_COUNT", "short": true  },
      { "title": "Date",           "value": "$DATE",          "short": true  }
    ]
  }]
}
JSON
)
  if curl -s -X POST -H 'Content-type: application/json' \
       --data "$SLACK_PAYLOAD" "$SLACK_WEBHOOK_URL" > /dev/null 2>&1; then
    echo -e "${GREEN}  Slack notification sent${RESET}"
  else
    echo -e "${YELLOW}  Slack notification failed (check SLACK_WEBHOOK_URL)${RESET}"
  fi
else
  echo -e "${YELLOW}  Slack: set SLACK_WEBHOOK_URL in .env to enable${RESET}"
fi

# ── MS Teams notification (optional) ─────────────────────────────────────────
if [[ -n "$TEAMS_WEBHOOK_URL" ]]; then
  TEAMS_PAYLOAD=$(cat <<JSON
{
  "@type": "MessageCard",
  "@context": "http://schema.org/extensions",
  "summary": "AI Session Complete",
  "themeColor": "0078D7",
  "title": "AI Session Complete — $AUTHOR",
  "sections": [{
    "facts": [
      { "name": "Branch",        "value": "$BRANCH"        },
      { "name": "Summary",       "value": "$SUMMARY"       },
      { "name": "Files Changed", "value": "$CHANGED_COUNT" },
      { "name": "Date",          "value": "$DATE"          }
    ]
  }]
}
JSON
)
  if curl -s -X POST -H 'Content-type: application/json' \
       --data "$TEAMS_PAYLOAD" "$TEAMS_WEBHOOK_URL" > /dev/null 2>&1; then
    echo -e "${GREEN}  Teams notification sent${RESET}"
  else
    echo -e "${YELLOW}  Teams notification failed (check TEAMS_WEBHOOK_URL)${RESET}"
  fi
else
  echo -e "${YELLOW}  Teams: set TEAMS_WEBHOOK_URL in .env to enable${RESET}"
fi

echo ""
exit 0
